{{- range .Values.pvcs }}
{{- if .name }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .storage | quote }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
