apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llama-stack.fullname" . }}-config
  labels:
    {{- include "llama-stack.labels" . | nindent 4 }}
data:
  config.yaml: |
    version: 2
    distro_name: tuw-ai
    {{- with .Values.apis }}
    apis:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.providers }}
    providers:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.storage }}
    storage:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.registeredResources }}
    registered_resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.server }}
    server:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vectorStores }}
    vector_stores:
      {{- toYaml . | nindent 6 }}
    {{- end }}
