{
 "title": "vLLM",
 "description": "Monitoring vLLM Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model_name",
    "query": {
     "query": "label_values(vllm:e2e_request_latency_seconds_count, model_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall P50 to P99 Request Latency",
   "type": "timeseries",
   "description": "Overall P50 to P99 request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Average Latency of Endpoints",
   "type": "timeseries",
   "description": "Average request latency of the endpoints measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{model_name=~\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average - {{model_name}}"
    }
   ]
  },
  {
   "title": "Prompt Token Throughput",
   "type": "timeseries",
   "description": "Number of Prompt tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec - {{model_name}}"
    }
   ]
  },
  {
   "title": "Generation Token Throughput",
   "type": "timeseries",
   "description": "Number of Generation tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vllm:generation_tokens_total{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec - {{model_name}}"
    }
   ]
  },
  {
   "title": "Overall P50 to P99 Time Per Output Token Latency",
   "type": "timeseries",
   "description": "Overall P50 to P99 time to output token latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Average Time Per Output Token Latency by Endpoint",
   "type": "timeseries",
   "description": "Average time to output token latency per endpoint in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:time_per_output_token_seconds_sum{model_name=~\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Mean - {{model_name}}"
    }
   ]
  },
  {
   "title": "Num Running Requests",
   "type": "timeseries",
   "description": "Number of requests in RUNNING state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vllm:num_requests_running{model_name=~\"$model_name\"}",
     "legendFormat": "Num Running - {{model_name}}"
    }
   ]
  },
  {
   "title": "Num Swapped Requests",
   "type": "timeseries",
   "description": "Number of requests in SWAPPED state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vllm:num_requests_swapped{model_name=~\"$model_name\"}",
     "legendFormat": "Num Swapped - {{model_name}}"
    }
   ]
  },
  {
   "title": "Num Waiting Requests",
   "type": "timeseries",
   "description": "Number of requests in WAITING state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vllm:num_requests_waiting{model_name=~\"$model_name\"}",
     "legendFormat": "Num Waiting - {{model_name}}"
    }
   ]
  },
  {
   "title": "Overall P50 to P99 Time To First Token Latency",
   "type": "timeseries",
   "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Average Latency of Endpoints",
   "type": "timeseries",
   "description": "Average TTFT latency in seconds for each endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:time_to_first_token_seconds_sum{model_name=~\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average - {{model_name}}"
    }
   ]
  },
  {
   "title": "GPU Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used GPU cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{model_name=~\"$model_name\"}",
     "legendFormat": "GPU Cache Usage - {{model_name}}"
    }
   ]
  },
  {
   "title": "CPU Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of used CPU cache blocks by vLLM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:cpu_cache_usage_perc{model_name=~\"$model_name\"}",
     "legendFormat": "CPU Cache Usage - {{model_name}}"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "description": "Heatmap of request prompt length",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=~\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}} - {{model_name}}"
    }
   ]
  },
  {
   "title": "Request Generation Length",
   "type": "heatmap",
   "description": "Heatmap of request generation length",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=~\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Finish Reason",
   "type": "timeseries",
   "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=~\"$model_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(vllm:request_queue_time_seconds_sum{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Queue Time in Sec  - {{model_name}}"
    }
   ]
  },
  {
   "title": "Requests Prefill Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(vllm:request_prefill_time_seconds_sum{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Prefill - {{model_name}}"
    }
   ]
  },
  {
   "title": "Requests Decode Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(vllm:request_decode_time_seconds_sum{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Decode - {{model_name}}"
    }
   ]
  },
  {
   "title": "Max Generation Token in Sequence Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(vllm:request_max_num_generation_tokens_sum{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Tokens - {{model_name}}"
    }
   ]
  }
 ]
}