{{- $smtp := index .Values "kube-prometheus-stack" "alertmanager" "smtp" | default dict -}}
{{- if and $smtp.enabled $smtp.secretName $smtp.vaultKey $smtp.vaultProperty }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $smtp.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: datalab-vault
    kind: ClusterSecretStore
  target:
    name: {{ $smtp.secretName }}
  data:
  - secretKey: smtp_password
    remoteRef:
      key: {{ $smtp.vaultKey }}
      property: {{ $smtp.vaultProperty }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
{{- end }}
