{
 "title": "vLLM Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "model_name",
    "query": {
     "query": "label_values(vllm:e2e_request_latency_seconds_count, model_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview System Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Tokens Processed",
   "type": "stat",
   "description": "Total number of prompt tokens processed within the specified time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vllm:prompt_tokens_total{model_name=~\"$model_name\"}[$__range]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Output Tokens Generated",
   "type": "stat",
   "description": "Total number of output tokens generated within the specified time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vllm:generation_tokens_total{model_name=~\"$model_name\"}[$__range]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "stat",
   "description": "Average Latency by Model",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(model_name) (vllm:e2e_request_latency_seconds_sum{model_name=~\"$model_name\"}) / avg by(model_name) (vllm:e2e_request_latency_seconds_count{model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Request latency distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:e2e_request_latency_seconds_bucket{model_name=~\"$model_name\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Input Tokens Processed (per model)",
   "type": "bargauge",
   "description": "Total number of prompt tokens processed within the specified time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vllm:prompt_tokens_total{model_name=~\"$model_name\"}[$__range])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Output Tokens Generated (per model)",
   "type": "bargauge",
   "description": "Total number of output tokens generated within the specified time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vllm:generation_tokens_total{model_name=~\"$model_name\"}[$__range])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  { "title": "Serving Engine Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Number of Running Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "vllm:num_requests_running{model_name=~\"$model_name\"}",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Number of Pending Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "vllm:num_requests_waiting{model_name=~\"$model_name\"}",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Input Tokens Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "increase(vllm:prompt_tokens_total{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Output Tokens Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "increase(vllm:generation_tokens_total{model_name=~\"$model_name\"}[$__rate_interval])",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "GPU KV Usage",
   "type": "timeseries",
   "description": "Percentage of the Key-Value cache space used on the GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:gpu_cache_usage_perc{model_name=~\"$model_name\"}",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "KV Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(model_name) (vllm:prefix_cache_hits_total{model_name=~\"$model_name\"}) / avg by(model_name) (vllm:prompt_tokens_total{model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  { "title": "QoS Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Average TTFT",
   "type": "timeseries",
   "description": "Average Time-to-first-token by model",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(model_name, pod) (vllm:time_to_first_token_seconds_sum{model_name=~\"$model_name\"}) / avg by(model_name, pod) (vllm:time_to_first_token_seconds_count{model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Router-side Queueing Delay",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(model_name, pod) (vllm:request_queue_time_seconds_sum{model_name=~\"$model_name\"}) / avg by(model_name, pod) (vllm:request_queue_time_seconds_count{model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Request TTFT distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (vllm:time_to_first_token_seconds_bucket{model_name=~\"$model_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Prefill Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(model_name, pod) (vllm:request_prefill_time_seconds_sum{model_name=~\"$model_name\"}) / avg by(model_name, pod) (vllm:request_prefill_time_seconds_count{model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Average Inter-Token Latency (ITL)",
   "type": "timeseries",
   "description": "Average Inter-Token Latency",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(model_name, pod) (vllm:inter_token_latency_seconds_sum{model_name=~\"$model_name\"}) / avg by(model_name, pod) (vllm:inter_token_latency_seconds_count{model_name=~\"$model_name\"})",
     "legendFormat": "{{model_name}} - {{pod}}"
    }
   ]
  }
 ]
}